name: pythonworkflow
on: workflow_dispatch

jobs:
        datapipeline:
                name: data_pipeline
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout code
                          uses: actions/checkout@v4

                        - name: install python
                          uses: actions/setup-python@v4
                          with:
                                  python-version: '3.10'
                        - name: clean_data
                          run: |
                                cd ModelCleaning
                                pip install -r requirements.txt
                                python Cleandata.py

                        - name: train_test_dataset
                          run: python ModelCleaning/train_test_dataset.py






