name: tutorial2
on: workflow_dispatch

jobs:
    job1:
        name: job1
        runs-on: ubuntu-latest
        steps: 
          - name: setup
            run: |
                echo date
                pwd
                ls -a
    job2:
        name: job2
        runs-on: ubuntu_latest
        steps:
          - name: setup python
            uses: actions/setup-python@v4
            with: 
              python-version: 3.9
            
          - name: set up pandas
            run: pip3 install pandas
          - name: create artefact
            run: |
               touch artifact.py
               echo "# This is my python artifact" > artifact.py 
               pyhton3.9 artifact.py
